---

- hosts: all
  become: True
  gather_facts: False

  tasks:

    - vars:
        users:
          - login: thy
            name: Thierry Delamare
            github: thyepi
          - login: cedric
            name: Cédric Girard
            github: senseicoder
          - login: evens
            name: Evens Solignac
            github: slgevens

      block:

      - user:
          name: &login '{{ item.login }}'
          comment: '{{ item.name }}'
          groups: [ adm, sudo-nopasswd ]
          append: True
          shell: /bin/bash
        with_items: '{{ users }}'

      - authorized_key:
          user: *login
          key: https://github.com/{{ item.github }}.keys
        with_items: '{{ users }}'
