---

- hosts: all
  become: True
  gather_facts: False

  tasks:

    - assert:
        that: |-
          lookup('env', 'PACKER_DEBIAN_PASSWD') != ''

    - vars:
        user:
          login: thy
          name: &name Thierry Delamare
          github: thyepi

      block:

      - user:
          name: &login '{{ user.login }}'
          comment: *name
          groups: [ adm ]
          append: True
          shell: /bin/bash
          update_password: on_create
          password: |-
            {{ lookup('passwordstore', 'packer/' + inventory_hostname + '/' + user.login) }}

      - authorized_key:
          user: *login
          key: https://github.com/{{ user.github }}.keys
